---
version: '3.7'

services:
  postgres:
    image: postgres:10
    container_name: pg01
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "25432:5432"
    volumes:
      - ../../postgres_data:/var/lib/postgresql/data/

  redis:
   image: redis:latest
   container_name: rd01
   ports:
     - '6379:6379'

  moderation_worker:
    scale: 1
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
    command: celery -A moderation_worker worker -n moderation_worker_%n --loglevel=INFO
    depends_on:
      - postgres
      - redis
  flower:
    image: mher/flower:latest
    ports:
      - '5555:5555'
    environment:
      - CELERY_BROKER_URL=redis://rd01:6379
    depends_on:
      - redis

  moderation_web:
    container_name: moderation_web01
    ports:
      - '5001:5001'
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn moderation_api:app --reload --host=0.0.0.0 --port=5001

  web:
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ['/app/entrypoint.sh']
    depends_on:
      - postgres
      - redis
